Greenit/Controllers/ChannelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Greenit.Data;
using Greenit.Models;
using Greenit.Services;
using System.Text;

namespace Greenit.Controllers
{
    public class ChannelsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IChannelService _ChannelService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IHostingEnvironment hostingEnvironment;


        public ChannelsController(IChannelService ChannelService, UserManager<IdentityUser> userManager, 
            ApplicationDbContext context)
        {
            _ChannelService = ChannelService;
            _userManager = userManager;
            _context = context ?? throw new ArgumentNullException(nameof(context));
        }

        // GET: Channels
        public async Task<IActionResult> Index() { 
            var currentUser = await _userManager.GetUserAsync(User);
       
            var items = await _ChannelService.GetChannelsAsync();

            return View(items);
        
            //return View(await _context.Channels.ToListAsync());
        }

        [HttpGet, Route("Channels/{id?}/{slug}")]
        public async Task<IActionResult> Details(int? id, string slug)
        {
            if (id == null)
            {
                return NotFound();
            }

            var channel = await _context.Channels
                .Include(c=>c.posts)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (channel == null)
            {
                return NotFound();
            }

            return View(channel);
        }

        // GET: Channels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Channels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = MyIdentityData.BlogPolicy_Add)]
        public async Task<IActionResult> Create([Bind("Id,Name")] Channel channel)
        {
            if (ModelState.IsValid)
            {
                channel.Slug = Friendly(channel.Name);
                channel.UserId = User.Identity.Name;
                _userManager.AddToRoleAsync(await _userManager.FindByEmailAsync(channel.UserId), "ChannelAdmin");
                _context.Add(channel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(channel);
        }

        // GET: Channels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var channel = await _context.Channels.FindAsync(id);
            if (channel == null)
            {
                return NotFound();
            }
            return View(channel);
        }

        // POST: Channels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Channel channel)
        {
            if (id != channel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(channel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChannelExists(channel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(channel);
        }



        private bool ChannelExists(int id)
        {
            return _context.Channels.Any(e => e.Id == id);
        }

        [HttpPost]
        [Authorize(Policy = MyIdentityData.BlogPolicy_Add)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPost([Bind("Id,ChannelId,Title,Body,Posted")] BlogPost blogPost)
        {
            if (ModelState.IsValid)
            {
                blogPost.Slug = Friendly(blogPost.Title);
                blogPost.UserId = User.Identity.Name;
                blogPost.Posted = DateTime.Now;
                var channel = await _context.Channels.Where(p => p.Id == blogPost.ChannelId)
                                                .Include(p => p.posts)
                                                .FirstOrDefaultAsync();
                _context.Add(blogPost);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(blogPost);
        }

        public static string Friendly(string title)
        {
            if (title == null) return "";

            const int maxlen = 80;
            int len = title.Length;
            bool prevdash = false;
            var sb = new StringBuilder(len);
            char c;

            for (int i = 0; i < len; i++)
            {
                c = title[i];
                if ((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9'))
                {
                    sb.Append(c);
                    prevdash = false;
                }
                else if (c >= 'A' && c <= 'Z')
                {
                    // tricky way to convert to lowercase
                    sb.Append((char)(c | 32));
                    prevdash = false;
                }
                else if (c == ' ' || c == ',' || c == '.' || c == '/' ||
                    c == '\\' || c == '-' || c == '_' || c == '=')
                {
                    if (!prevdash && sb.Length > 0)
                    {
                        sb.Append('-');
                        prevdash = true;
                    }
                }
                else if ((int)c >= 128)
                {
                    int prevlen = sb.Length;
                    sb.Append(RemapInternationalCharToAscii(c));
                    if (prevlen != sb.Length) prevdash = false;
                }
                if (i == maxlen) break;
            }

            if (prevdash)
                return sb.ToString().Substring(0, sb.Length - 1);
            else
                return sb.ToString();
        }

        public static string RemapInternationalCharToAscii(char c)
        {
            string s = c.ToString().ToLowerInvariant();
            if ("àåáâäãåą".Contains(s))
            {
                return "a";
            }
            else if ("èéêëę".Contains(s))
            {
                return "e";
            }
            else if ("ìíîïı".Contains(s))
            {
                return "i";
            }
            else if ("òóôõöøőð".Contains(s))
            {
                return "o";
            }
            else if ("ùúûüŭů".Contains(s))
            {
                return "u";
            }
            else if ("çćčĉ".Contains(s))
            {
                return "c";
            }
            else if ("żźž".Contains(s))
            {
                return "z";
            }
            else if ("śşšŝ".Contains(s))
            {
                return "s";
            }
            else if ("ñń".Contains(s))
            {
                return "n";
            }
            else if ("ýÿ".Contains(s))
            {
                return "y";
            }
            else if ("ğĝ".Contains(s))
            {
                return "g";
            }
            else if (c == 'ř')
            {
                return "r";
            }
            else if (c == 'ł')
            {
                return "l";
            }
            else if (c == 'đ')
            {
                return "d";
            }
            else if (c == 'ß')
            {
                return "ss";
            }
            else if (c == 'Þ')
            {
                return "th";
            }
            else if (c == 'ĥ')
            {
                return "h";
            }
            else if (c == 'ĵ')
            {
                return "j";
            }
            else
            {
                return "";
            }
        }
    }
}

Greenit/Controllers/ManageusersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using AspNetCoreTodo.Models;
using Microsoft.EntityFrameworkCore;
namespace AspNetCoreTodo.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ManageUsersController : Controller
    {
        private readonly UserManager<IdentityUser>
        _userManager;
        public ManageUsersController(
        UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var admins = (await _userManager
            .GetUsersInRoleAsync("Administrator"))
            .ToArray();
            var everyone = await _userManager.Users
            .ToArrayAsync();
            var model = new ManageUsersViewModel
            {
                Administrators = admins,
                Everyone = everyone
            };
            return View(model);
        }
    }
}

Greenit/Controllers/StatsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Greenit.Data;
using Greenit.Models;
using Greenit.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Greenit.Controllers
{
    public class StatsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IBlogItemService _blogItemService;
        private readonly IChannelService _channelService;
        private readonly UserManager<IdentityUser> _userManager;


        public StatsController(IChannelService channelService, IBlogItemService blogItemService,
           UserManager<IdentityUser> userManager, ApplicationDbContext context)
        {
            _blogItemService = blogItemService;
            _channelService = channelService;
            _userManager = userManager;
            _context = context ?? throw new ArgumentNullException(nameof(context));
        }
        public async Task<IActionResult> Index()
        {
            StatsViewModel statsView = new StatsViewModel();
            //statsView.blogPosts 

            var blogs = await _blogItemService.GetBlogPostAsync();
            var channels = await _channelService.GetChannelsAsync();
            var comments = await _blogItemService.GetCommentsAsync();

            statsView.blogPostslSize = blogs.Length;
            statsView.channelsSize = channels.Length;
            statsView.commentsSize = comments.Length;
            statsView.indvComments = await _blogItemService.GetCommentCountByUserAsync();
            statsView.indvPosts = await _blogItemService.GetPostCountByUserAsync();
            statsView.mostRecentComment = await _context.comments.OrderByDescending(c => c.Posted).Take(1).ToArrayAsync();

            return View(statsView);
        }
    }
}

Greenit/Controllers/UserManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Greenit.Data;
using Greenit.Models;
using Greenit.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace Greenit.Controllers
{
    public class UserManagerController:  Controller
    {
        private readonly IBlogItemService _BlogService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly SignInManager<IdentityUser> SignInManager;

        public UserManagerController(IBlogItemService BlogService,
            UserManager<IdentityUser> userManager, ApplicationDbContext context)
        {
            _BlogService = BlogService;
            _userManager = userManager;
            _context = context ?? throw new ArgumentNullException(nameof(context));
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterUser ([Bind("Email,Password")] UserModel user)
        {
            IdentityUser User = new IdentityUser(user.Email);
            User.Email = user.Email;
            User.NormalizedEmail = user.Email.ToUpper();
            
            _userManager.CreateAsync(User,user.Password);
            _userManager.AddToRoleAsync(User, "Contributor");

            return View("../Home/Index");
        }

        
        [Authorize(Policy = MyIdentityData.BlogPolicy_Delete)]
        public async Task<IActionResult> GetUserLists()
        {
            var userslist = await _userManager.Users.ToListAsync();

            List<UserModel> userslist2 = new List<UserModel>();

            foreach(var bob in userslist)
            {
                userslist2.Add(new UserModel { Email = bob.Email });
            }

            return View(userslist2);
        }
        

        [Authorize(Policy = MyIdentityData.BlogPolicy_Delete)]
        public async Task<IActionResult> BlockUserFromSite(string user)
        {
            IdentityUser RemovedUser = await _userManager.FindByEmailAsync(user);

            await _userManager.RemoveFromRoleAsync(RemovedUser, "Administrator");
            await _userManager.RemoveFromRoleAsync(RemovedUser, "Contributor");
            



            return View("../Home/Index");
        }



        [Authorize(Policy = MyIdentityData.BlogPolicy_Delete)]
        public async Task<IActionResult> UnblockUserFromSite(string user)
        {
            var RemovedUser = await _userManager.FindByEmailAsync(user);

            await _userManager.AddToRoleAsync(RemovedUser, "Contributor");

            return View("../Home/Index");
        }
    }
}

Greenit/Views/Shared/AdminActionsPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using AspNetCoreTodo.Models
@using AspNetCoreTodo
@inject SignInManager<IdentityUser> signInManager
@inject UserManager<IdentityUser> userManager
@if (signInManager.IsSignedIn(User))
{
    var currentUser = await userManager.GetUserAsync(User);
    var isAdmin = currentUser != null
    && await userManager.IsInRoleAsync(
    currentUser,
    Constants.AdministratorRole);
    if (isAdmin)
    {
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a asp-controller="ManageUsers"
                   asp-action="Index">
                    Manage Users
                </a>
            </li>
        </ul>
    }
}

Greenit/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService Authorization
@{
    var canDelete = (await Authorization.AuthorizeAsync(User, MyIdentityData.BlogPolicy_Delete)).Succeeded;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Greenit</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">

                <a style="font-size: x-large" class="navbar-brand" asp-area="" asp-controller="Channels" asp-action="Index"><img src="~/images/greenit.png" height="30px" width="110px"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @{ if (canDelete)
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="UserManager" asp-action="GetUserLists">Manage Users</a>
                                }
                            }
                        </li>
                        <li class="nav-item">
                            @{ if (canDelete)
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Stats" asp-action="Index">Site Stats</a>
                                }
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Greenit Vanegas - <a asp-area="" asp-controller="Channels" asp-action="Index">Home Page</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <!-- existing code here -->
        </ul>
        @await Html.PartialAsync("_LoginPartial")
        @await Html.PartialAsync("AdminActionsPartial")
    </div>

</body>
</html>