Greenit/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Greenit.Data;
using Greenit.Models;
using Greenit.Services;
using Microsoft.AspNetCore.Authorization; 
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;
using System.Text;

namespace Greenit.Controllers
{
    //[Authorize]
    public class BlogPostsController : Controller
    {
        private readonly IBlogItemService _BlogService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment hostingEnvironment;

        public BlogPostsController(IBlogItemService BlogService,
            UserManager<IdentityUser> userManager, ApplicationDbContext context)
        {
            _BlogService = BlogService;
            _userManager = userManager;
            _context = context ?? throw new ArgumentNullException(nameof(context));
        }

        

    public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            //if (currentUser == null) return Challenge();

            //this was var items = await _BlogService.GetBlogPostAsync(currentUser);
            var items = await _BlogService.GetBlogPostAsync();

            return View(items);

            //var currentUser = await _userManger.GetUserAsync(User); 
        }

        [HttpGet, Route("BlogPosts/Details/{id?}/{slug}")]
        public async Task<IActionResult> Details(int? id, string slug)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPosts
                .Include(c => c.Comments)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        // GET: BlogPosts/Create
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Policy = MyIdentityData.BlogPolicy_Edit)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPosts.FindAsync(id);
            //blogPost.Posted = DateTime.Now;
            if (blogPost == null)
            {
                return NotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Policy = MyIdentityData.BlogPolicy_Edit)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Body,Posted")] BlogPost blogPost)
        {
            if (id != blogPost.Id)
            {
                return NotFound();
            }

                if (ModelState.IsValid)
                {
                    try
                    {
                        blogPost.Posted = DateTime.Now;
                        _context.Update(blogPost);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!BlogPostExists(blogPost.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(blogPost);
            }

        // GET: BlogPosts/Delete/5
        [Authorize(Policy = MyIdentityData.BlogPolicy_Delete)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

                var blogPost = await _context.BlogPosts
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (blogPost == null)
                {
                    return NotFound();
                }

                return View(blogPost);
            }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blogPost = await _context.BlogPosts.FindAsync(id);
            _context.BlogPosts.Remove(blogPost);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogPostExists(int id)
        {
            return _context.BlogPosts.Any(e => e.Id == id);
        }

        [HttpPost]
        [Authorize(Policy = MyIdentityData.BlogPolicy_Add)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddComment([Bind("Id,UserId,PostId,Body,Posted")] Comment comment)
        {
            if (ModelState.IsValid)
            {

                comment.UserId = User.Identity.Name;
                comment.Posted = DateTime.Now;


                var Post = await _context.BlogPosts.Where(p => p.Id == comment.PostId)
                                                .Include(p => p.Comments)
                                                .FirstOrDefaultAsync();
                Post.Comments.Add(comment);
                await _context.SaveChangesAsync();
                string url = "Details/" + comment.PostId+"/"+Post.Slug;
                return Redirect(Url.RouteUrl("Details") + url);
            }
            return View(comment);
        }

    }
}

Greenit/Controllers/ChannelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Greenit.Data;
using Greenit.Models;
using Greenit.Services;
using System.Text;

namespace Greenit.Controllers
{
    public class ChannelsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IChannelService _ChannelService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IHostingEnvironment hostingEnvironment;


        public ChannelsController(IChannelService ChannelService, UserManager<IdentityUser> userManager, 
            ApplicationDbContext context)
        {
            _ChannelService = ChannelService;
            _userManager = userManager;
            _context = context ?? throw new ArgumentNullException(nameof(context));
        }

        // GET: Channels
        public async Task<IActionResult> Index() { 
            var currentUser = await _userManager.GetUserAsync(User);
       
            var items = await _ChannelService.GetChannelsAsync();

            return View(items);
        
            //return View(await _context.Channels.ToListAsync());
        }

        [HttpGet, Route("Channels/{id?}/{slug}")]
        public async Task<IActionResult> Details(int? id, string slug)
        {
            if (id == null)
            {
                return NotFound();
            }

            var channel = await _context.Channels
                .Include(c=>c.posts)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (channel == null)
            {
                return NotFound();
            }

            return View(channel);
        }

        // GET: Channels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Channels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = MyIdentityData.BlogPolicy_Add)]
        public async Task<IActionResult> Create([Bind("Id,Name")] Channel channel)
        {
            if (ModelState.IsValid)
            {
                channel.Slug = Friendly(channel.Name);
                channel.UserId = User.Identity.Name;
                _userManager.AddToRoleAsync(await _userManager.FindByEmailAsync(channel.UserId), "ChannelAdmin");
                _context.Add(channel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(channel);
        }

        // GET: Channels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var channel = await _context.Channels.FindAsync(id);
            if (channel == null)
            {
                return NotFound();
            }
            return View(channel);
        }

        // POST: Channels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Channel channel)
        {
            if (id != channel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(channel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChannelExists(channel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(channel);
        }



        private bool ChannelExists(int id)
        {
            return _context.Channels.Any(e => e.Id == id);
        }

        [HttpPost]
        [Authorize(Policy = MyIdentityData.BlogPolicy_Add)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPost([Bind("Id,ChannelId,Title,Body,Posted")] BlogPost blogPost)
        {
            if (ModelState.IsValid)
            {
                blogPost.Slug = Friendly(blogPost.Title);
                blogPost.UserId = User.Identity.Name;
                blogPost.Posted = DateTime.Now;
                var channel = await _context.Channels.Where(p => p.Id == blogPost.ChannelId)
                                                .Include(p => p.posts)
                                                .FirstOrDefaultAsync();
                _context.Add(blogPost);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(blogPost);
        }

        public static string Friendly(string title)
        {
            if (title == null) return "";

            const int maxlen = 80;
            int len = title.Length;
            bool prevdash = false;
            var sb = new StringBuilder(len);
            char c;

            for (int i = 0; i < len; i++)
            {
                c = title[i];
                if ((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9'))
                {
                    sb.Append(c);
                    prevdash = false;
                }
                else if (c >= 'A' && c <= 'Z')
                {
                    // tricky way to convert to lowercase
                    sb.Append((char)(c | 32));
                    prevdash = false;
                }
                else if (c == ' ' || c == ',' || c == '.' || c == '/' ||
                    c == '\\' || c == '-' || c == '_' || c == '=')
                {
                    if (!prevdash && sb.Length > 0)
                    {
                        sb.Append('-');
                        prevdash = true;
                    }
                }
                else if ((int)c >= 128)
                {
                    int prevlen = sb.Length;
                    sb.Append(RemapInternationalCharToAscii(c));
                    if (prevlen != sb.Length) prevdash = false;
                }
                if (i == maxlen) break;
            }

            if (prevdash)
                return sb.ToString().Substring(0, sb.Length - 1);
            else
                return sb.ToString();
        }

        public static string RemapInternationalCharToAscii(char c)
        {
            string s = c.ToString().ToLowerInvariant();
            if ("àåáâäãåą".Contains(s))
            {
                return "a";
            }
            else if ("èéêëę".Contains(s))
            {
                return "e";
            }
            else if ("ìíîïı".Contains(s))
            {
                return "i";
            }
            else if ("òóôõöøőð".Contains(s))
            {
                return "o";
            }
            else if ("ùúûüŭů".Contains(s))
            {
                return "u";
            }
            else if ("çćčĉ".Contains(s))
            {
                return "c";
            }
            else if ("żźž".Contains(s))
            {
                return "z";
            }
            else if ("śşšŝ".Contains(s))
            {
                return "s";
            }
            else if ("ñń".Contains(s))
            {
                return "n";
            }
            else if ("ýÿ".Contains(s))
            {
                return "y";
            }
            else if ("ğĝ".Contains(s))
            {
                return "g";
            }
            else if (c == 'ř')
            {
                return "r";
            }
            else if (c == 'ł')
            {
                return "l";
            }
            else if (c == 'đ')
            {
                return "d";
            }
            else if (c == 'ß')
            {
                return "ss";
            }
            else if (c == 'Þ')
            {
                return "th";
            }
            else if (c == 'ĥ')
            {
                return "h";
            }
            else if (c == 'ĵ')
            {
                return "j";
            }
            else
            {
                return "";
            }
        }
    }
}

Greenit/Views/Channels/AddPostPartial.cshtml
@model Greenit.Models.BlogPost

@{
    ViewData["Title"] = "AddPostPartial";
}

<h1>Add A Post</h1>

<h4>BlogPost</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddPost">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" value="@Model.ChannelId" asp-for="ChannelId" />
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <textarea asp-for="Body" class="form-control" rows="10" cols="40" placeholder="Write your entry here..."></textarea>
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Greenit/Views/Channels/Create.cshtml
@model Greenit.Models.Channel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Channel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Greenit/Views/Channels/Delete.cshtml
@*@model Greenit.Models.Channel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Channel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>*@

Greenit/Views/Channels/Details.cshtml
@model Greenit.Models.Channel
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService Authorization
@{
    ViewData["Title"] = "Details";
}
@{
    var canEdit = (await Authorization.AuthorizeAsync(User, MyIdentityData.BlogPolicy_Edit)).Succeeded;
}
@{
    var canAdd = (await Authorization.AuthorizeAsync(User, MyIdentityData.BlogPolicy_Add)).Succeeded;
}

<h1>Details</h1>

<div>

    <h5><i>&nbsp&nbsp&nbsp&nbspChannel:  @Html.DisplayFor(modelItem => Model.Name)</i></h5>
    <hr />

    <h3>Posts:</h3>
    <br />
    @if (Model.posts != null && Model.posts.Any())
    {
        @foreach (var post in Model.posts)
        {<a class="letteredChannel" asp-controller="BlogPosts" asp-action="Details" asp-route-id="@post.Id" asp-route-slug="@post.Slug">
             <h5>
                 &nbsp&nbsp&nbsp&nbsp<img src="~/images/blog_icon.png" height="30px" width="30px" />
                 @post.Title
             </h5><br>
         </a>
        }
    }
</div>
<div>
    @if (canEdit)
    {
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit Channel Name |</a> 
    }

    <a asp-action="Index">Back to List</a>
</div>
<br />
@if (canAdd)
{

    @Html.Partial("AddPostPartial.cshtml", new BlogPost() { ChannelId = Model.Id });
}

Greenit/Views/Channels/Edit.cshtml
@model Greenit.Models.Channel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Channel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Greenit/Views/Channels/Index.cshtml
@model IEnumerable<Greenit.Models.Channel>
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService Authorization
@{
    ViewData["Title"] = "Index";
}
@{
    var canAdd = (await Authorization.AuthorizeAsync(User, MyIdentityData.BlogPolicy_Add)).Succeeded;
}
@{
    var canEdit = (await Authorization.AuthorizeAsync(User, MyIdentityData.BlogPolicy_Edit)).Succeeded;
}

<h1>Channels</h1>

<p>
    @if(canAdd){ 
        <br />
    <button class="btn btn-success"><a asp-action="Create">Create New</a></button>
    }
    <br /><br />
    
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a class="letteredChannel" asp-controller="Channels" asp-action="Details" asp-route-id="@item.Id" asp-route-slug="@item.Slug">
                        <img src="~/images/blog-icon.png" height="30px" width="37px" />
                        @Html.DisplayFor(modelItem => item.Name)
                    </a>
</td>
                <td>
                    @if (canEdit) {
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    }
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>